import {
  renderApp,
  defaultPlannedMealRepository,
  defaultShoppingRepository,
  defaultFeatureFlagRepository,
  defaultPantryRepository,
  defaultRecipeRepository,
} from '../../renderApp'
import { toLocalIsoDate } from '../../../src/domain/meal-plans/week'
import '@fontsource/cormorant-garamond/latin-500.css'
import '@fontsource/space-grotesk/latin-400.css'
import '@fontsource/space-grotesk/latin-500.css'
import '@fontsource/space-grotesk/latin-700.css'
import '../../../src/styles/global.css'
const householdId = '20000000-0000-4000-8000-000000000001'
const params = new URLSearchParams(location.search)
const recipe = {
  ...(await defaultRecipeRepository.list(householdId))[0]!,
  name: 'Family lentil soup',
  sourceUrl: 'https://example.invalid/lentil-soup',
  authorName: 'Synthetic Cook',
  servings: 4,
  prepTimeMinutes: 10,
  cookTimeMinutes: 20,
  ingredients: '2 carrots\n1 cup lentils',
  description: 'Chop the carrots.\nSimmer until tender.',
  tags: [],
}
const planner = {
  ...defaultPlannedMealRepository,
  listWeek: async () =>
    params.has('empty')
      ? []
      : [
          {
            ...(await defaultPlannedMealRepository.create(householdId, {
              title: recipe.name,
              mealDate: toLocalIsoDate(new Date()),
              mealType: 'dinner',
              notes: null,
              recipeId: recipe.id,
              recipeSource: 'household',
            })),
            recipeState: {
              kind: 'active' as const,
              recipe: { id: recipe.id, name: recipe.name, archivedAt: null },
            },
          },
        ],
}
const milk = await defaultShoppingRepository.create(householdId, {
  name: 'Milk',
  quantity: 1,
  unit: 'L',
  category: 'dairy_and_eggs',
})
const shopping = {
  ...defaultShoppingRepository,
  list: async () => (params.has('empty') ? [] : [{ ...milk, completed: true }]),
}
const pantry = {
  ...defaultPantryRepository,
  list: async () => [
    {
      id: 'milk',
      householdId,
      name: 'Milk',
      category: 'dairy' as const,
      categorySource: 'explicit' as const,
      storageLocation: 'fridge' as const,
      storageLocationSource: 'explicit' as const,
      classificationVersion: null,
      quantity: 1,
      unit: 'item',
      available: true,
      isDefault: false,
      updatedAt: '2026-10-06',
    },
  ],
}
renderApp(
  '/',
  undefined,
  undefined,
  undefined,
  undefined,
  pantry,
  planner,
  undefined,
  { ...defaultRecipeRepository, list: async () => [recipe] },
  shopping,
  { ...defaultFeatureFlagRepository, isAdmin: async () => !params.has('member') },
  {
    getCurrentPlan: async () => {
      throw new Error('Not generated by this synthetic Home test')
    },
  },
)
