import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { format, resolveConfig } from 'prettier'

const outputPath = join(
  process.cwd(),
  'src',
  'infrastructure',
  'database',
  'generated',
  'database.types.ts',
)
const commandArgs = ['gen', 'types', '--local', '--lang', 'typescript', '--schema', 'cooksmith']
const generatedHeader =
  '// Generated from local Supabase by `npm run db:types`. Do not edit this file manually.\n\n'

export function generateTypes() {
  const result = spawnSync('supabase', commandArgs, {
    encoding: 'utf8',
    env: { ...process.env, SUPABASE_TELEMETRY_DISABLED: '1' },
  })

  if (result.status !== 0) {
    process.stderr.write(result.stderr || 'Supabase database type generation failed.\n')
    process.exit(result.status ?? 1)
  }

  return result.stdout
}

const mode = process.argv[2]
const prettierConfig = (await resolveConfig(outputPath)) ?? {}
const generated = await format(`${generatedHeader}${generateTypes()}`, {
  ...prettierConfig,
  filepath: outputPath,
})

if (mode === 'write') {
  writeFileSync(outputPath, generated)
  process.stdout.write('Generated and formatted local Cooksmith database types.\n')
} else if (mode === 'check') {
  const committed = readFileSync(outputPath, 'utf8')

  if (generated !== committed) {
    process.stderr.write(
      'Generated database types are stale. Run `npm run db:types` with local Supabase running and commit the result.\n',
    )
    process.exit(1)
  }

  process.stdout.write('Generated local Cooksmith database types are current.\n')
} else {
  process.stderr.write('Expected database type mode: write or check.\n')
  process.exit(1)
}
