import { useMemo, useState } from 'react'
import { BookOpen, CalendarDays, Check, ChevronLeft, ExternalLink, Flame, Home, ListChecks, PackageOpen, Plus, Search, ShoppingBasket, Trash2, X } from 'lucide-react'
import { days, recipes as seeded } from './data'
import { useStoredState } from './hooks'
import type { PantryItem, Plan, Recipe } from './types'

type Tab = 'home'|'recipes'|'pantry'|'plan'|'shop'
const tabs: {id:Tab;label:string;icon:typeof Home}[]=[{id:'home',label:'Home',icon:Home},{id:'recipes',label:'Recipes',icon:BookOpen},{id:'pantry',label:'Pantry',icon:PackageOpen},{id:'plan',label:'Plan',icon:CalendarDays},{id:'shop',label:'Shop',icon:ShoppingBasket}]

export default function App(){
 const [tab,setTab]=useState<Tab>('home'); const [personal,setPersonal]=useStoredState<Recipe[]>('cooksmith-recipes',[]); const [pantry,setPantry]=useStoredState<PantryItem[]>('cooksmith-pantry',[]); const [plan,setPlan]=useStoredState<Plan>('cooksmith-plan',{}); const [view,setView]=useState<Recipe|null>(null); const [addRecipe,setAddRecipe]=useState(false)
 const all=[...personal,...seeded]
 const content=tab==='home'?<HomeView recipes={all} plan={plan} pantry={pantry} go={setTab} open={setView}/>:tab==='recipes'?<Recipes recipes={all} open={setView} add={()=>setAddRecipe(true)}/>:tab==='pantry'?<Pantry items={pantry} set={setPantry}/>:tab==='plan'?<Planner recipes={all} plan={plan} set={setPlan} open={setView}/>:<Shopping recipes={all} plan={plan} pantry={pantry}/>
 return <div className="app"><header><button className="brand" onClick={()=>setTab('home')}><span className="mark">C</span><span>COOKSMITH<small>Forge a better week</small></span></button><button className="avatar">RC</button></header><main>{content}</main><nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={21}/><span>{t.label}</span></button>)}</nav>{view&&<RecipeDetail recipe={view} close={()=>setView(null)}/>} {addRecipe&&<AddRecipe close={()=>setAddRecipe(false)} save={r=>{setPersonal([r,...personal]);setAddRecipe(false);setView(r)}}/>}</div>
}

function HomeView({recipes,plan,pantry,go,open}:{recipes:Recipe[];plan:Plan;pantry:PantryItem[];go:(t:Tab)=>void;open:(r:Recipe)=>void}){const planned=Object.values(plan).filter(Boolean).length;return <><section className="hero"><p className="eyebrow">SUNDAY, 12 JULY</p><h1>Righto. What’s for dinner?</h1><p>You’ve got enough decisions to make. Let’s make this one less annoying.</p><button className="primary" onClick={()=>go('plan')}>Plan the week <CalendarDays size={18}/></button></section><section className="week-card"><div><p className="eyebrow">THIS WEEK</p><h2>{planned?`${planned} meal${planned===1?'':'s'} sorted`:'A beautifully blank slate'}</h2><p>{planned?'Look at you. Practically organised.':'No, you don’t need to plan all seven nights.'}</p></div><button className="round" onClick={()=>go('plan')}>→</button></section><SectionTitle title="Quick wins" subtitle="Dinner without the dramatic subplot." action="See all" click={()=>go('recipes')}/><div className="card-row">{recipes.filter(r=>r.time<=25).slice(0,4).map(r=><RecipeCard key={r.id} recipe={r} open={open}/>)}</div><section className="pantry-call"><div className="pantry-icon">🥫</div><div><p className="eyebrow">THE PANTRY</p><h2>{pantry.length?`${pantry.length} things kicking around`:'What have you got?'}</h2><p>{pantry.length?'Keep it honest-ish. We won’t audit you.':'Add the basics. We’ll help make sense of the rest.'}</p></div><button onClick={()=>go('pantry')}>Have a look →</button></section></>}
function SectionTitle({title,subtitle,action,click}:{title:string;subtitle:string;action?:string;click?:()=>void}){return <div className="section-title"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button onClick={click}>{action} →</button>}</div>}
function RecipeCard({recipe,open}:{recipe:Recipe;open:(r:Recipe)=>void}){return <button className="recipe-card" onClick={()=>open(recipe)}><div className="food-art" style={{background:recipe.colour}}><span>{recipe.emoji}</span>{recipe.personal&&<b>YOURS</b>}</div><div className="recipe-info"><div className="tags">{recipe.tags.slice(0,2).map(t=><span key={t}>{t}</span>)}</div><h3>{recipe.title}</h3><p>{recipe.blurb}</p><small><Flame size={14}/>{recipe.time} mins · Serves {recipe.serves}</small></div></button>}

function Recipes({recipes,open,add}:{recipes:Recipe[];open:(r:Recipe)=>void;add:()=>void}){const [q,setQ]=useState('');const [filter,setFilter]=useState('All');const visible=recipes.filter(r=>(filter==='All'||(filter==='Mine'?r.personal:r.tags.includes(filter)))&&(r.title+r.tags.join(' ')).toLowerCase().includes(q.toLowerCase()));return <><div className="page-head"><div><p className="eyebrow">THE RECIPE FORGE</p><h1>Good food. Less faff.</h1><p>Reliable dinners for real weeks. Add your own winners too.</p></div><button className="primary" onClick={add}><Plus size={18}/> Add yours</button></div><div className="search"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search recipes (or type ‘chicken’ and hope)"/></div><div className="filters">{['All','Quick','Family','Veggie','Mine'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div>{visible.length?<div className="recipe-grid">{visible.map(r=><RecipeCard key={r.id} recipe={r} open={open}/>)}</div>:<Empty emoji="🫙" title="Nothing in that jar" text="Try another search. The recipe may be hiding behind the tahini."/>}</>}

function Pantry({items,set}:{items:PantryItem[];set:(v:PantryItem[])=>void}){const [name,setName]=useState('');const [amount,setAmount]=useState('');const add=()=>{if(name.trim()){set([{id:crypto.randomUUID(),name:name.trim(),amount:amount.trim()||'some'},...items]);setName('');setAmount('')}};return <><div className="page-head"><div><p className="eyebrow">THE PANTRY</p><h1>What’s kicking around?</h1><p>A rough list is plenty. This isn’t stocktake at Bunnings.</p></div></div><div className="add-strip"><input value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="e.g. tinned tomatoes"/><input value={amount} onChange={e=>setAmount(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="How much-ish?"/><button className="primary" onClick={add}><Plus size={18}/> Add</button></div>{items.length?<div className="list-card">{items.map(i=><div className="pantry-row" key={i.id}><button className={'tick '+(i.checked?'done':'')} onClick={()=>set(items.map(x=>x.id===i.id?{...x,checked:!x.checked}:x))}>{i.checked&&<Check size={16}/>}</button><div><b>{i.name}</b><span>{i.amount}</span></div><button className="delete" onClick={()=>set(items.filter(x=>x.id!==i.id))}><Trash2 size={18}/></button></div>)}</div>:<Empty emoji="🥫" title="Your pantry is playing hard to get" text="Add the basics you usually have kicking around. No need to confess the mystery jars."/>}</>}

function Planner({recipes,plan,set,open}:{recipes:Recipe[];plan:Plan;set:(p:Plan)=>void;open:(r:Recipe)=>void}){return <><div className="page-head"><div><p className="eyebrow">THE WEEKLY WRANGLE</p><h1>Seven days. Let’s not overthink it.</h1><p>Plan a few dinners, leave room for leftovers and the inevitable takeaway.</p></div></div><div className="plan-grid">{days.map((d,i)=>{const r=recipes.find(x=>x.id===plan[d]);return <div className="day" key={d}><div className="day-label"><b>{d}</b><span>{13+i} Jul</span></div>{r?<div className="planned" onClick={()=>open(r)}><span style={{background:r.colour}}>{r.emoji}</span><div><b>{r.title}</b><small>{r.time} mins</small></div><button onClick={e=>{e.stopPropagation();const n={...plan};delete n[d];set(n)}}><X size={17}/></button></div>:<select value="" onChange={e=>set({...plan,[d]:e.target.value})}><option value="">+ Add dinner</option>{recipes.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select>}</div>})}</div><div className="permission"><span>🍕</span><div><b>Plans change. That’s the plan.</b><p>People order takeaway. Vegetables become mysterious fridge sludge. Adjust whenever you need to.</p></div></div></>}

function Shopping({recipes,plan,pantry}:{recipes:Recipe[];plan:Plan;pantry:PantryItem[]}){const ingredients=useMemo(()=>{const map=new Map<string,string[]>();Object.values(plan).forEach(id=>recipes.find(r=>r.id===id)?.ingredients.forEach(i=>map.set(i.name,[...(map.get(i.name)||[]),i.amount])));return [...map.entries()].map(([name,amounts])=>({name,amount:amounts.join(' + '),have:pantry.some(p=>p.name.toLowerCase().includes(name.toLowerCase())||name.toLowerCase().includes(p.name.toLowerCase()))}))},[recipes,plan,pantry]);const [checked,setChecked]=useState<string[]>([]);return <><div className="page-head"><div><p className="eyebrow">THE SHOPPING LIST</p><h1>Righto. Here’s what you need.</h1><p>Check the pantry first, unless you’re building Australia’s largest private collection of tinned tomatoes.</p></div></div>{ingredients.length?<><div className="shop-summary"><ListChecks/><div><b>{ingredients.length-checked.length} things left</b><span>{ingredients.filter(i=>i.have).length} might already be in the pantry</span></div></div><div className="list-card">{ingredients.map(i=><button className={'shop-row '+(checked.includes(i.name)?'crossed':'')} key={i.name} onClick={()=>setChecked(checked.includes(i.name)?checked.filter(x=>x!==i.name):[...checked,i.name])}><span className="tick">{checked.includes(i.name)&&<Check size={16}/>}</span><span><b>{i.name}</b><small>{i.amount}</small></span>{i.have&&<em>CHECK PANTRY</em>}</button>)}</div></>:<Empty emoji="🛒" title="Nothing to buy. Suspicious." text="Add a few meals to your week and your shopping list will sort itself out."/>}</>}

function RecipeDetail({recipe,close}:{recipe:Recipe;close:()=>void}){return <div className="overlay"><article className="sheet"><button className="sheet-close" onClick={close}><ChevronLeft/> Back</button><div className="detail-art" style={{background:recipe.colour}}><span>{recipe.emoji}</span></div><div className="detail-body"><div className="tags">{recipe.tags.map(t=><span key={t}>{t}</span>)}</div><h1>{recipe.title}</h1><p className="lede">{recipe.blurb}</p><div className="stats"><span><b>{recipe.time}</b> minutes</span><span><b>{recipe.serves}</b> serves</span></div>{recipe.sourceUrl&&<a className="source" href={recipe.sourceUrl} target="_blank">Original recipe <ExternalLink size={16}/></a>}<h2>What you’ll need</h2><ul className="ingredients">{recipe.ingredients.map((i,n)=><li key={n}><span>{i.name}</span><b>{i.amount}</b></li>)}</ul><h2>Make it happen</h2><ol className="method">{recipe.method.map((m,n)=><li key={n}><span>{n+1}</span><p>{m}</p></li>)}</ol><div className="permission"><span>👌</span><div><b>Close enough counts.</b><p>Swap what you need. Dinner is not a laboratory experiment.</p></div></div></div></article></div>}

function AddRecipe({close,save}:{close:()=>void;save:(r:Recipe)=>void}){const [title,setTitle]=useState('');const [source,setSource]=useState('');const [ingredients,setIngredients]=useState('');const submit=()=>{if(!title.trim())return;save({id:crypto.randomUUID(),title:title.trim(),blurb:'A household classic. Or at least worth another go.',time:30,serves:4,tags:['Mine'],colour:'#8B6E59',emoji:'🍽️',personal:true,sourceUrl:source||undefined,ingredients:ingredients.split('\n').filter(Boolean).map(x=>{const [name,amount='some']=x.split('|');return{name:name.trim(),amount:amount.trim()}}),method:['Follow the original recipe or your own highly scientific instincts.']})};return <div className="overlay"><article className="modal"><div className="modal-head"><div><p className="eyebrow">ADD YOUR OWN</p><h2>Found a winner? Chuck it in.</h2></div><button onClick={close}><X/></button></div><label>Recipe name<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nan’s lasagne"/></label><label>Original recipe link <small>(optional)</small><input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://..."/></label><label>Ingredients <small>(one per line, use | before the amount)</small><textarea value={ingredients} onChange={e=>setIngredients(e.target.value)} placeholder={'tomatoes | 2 tins\nonion | 1\ngarlic | 3 cloves'}/></label><button className="primary wide" onClick={submit}>Forge and file it</button><p className="form-note">No, you don’t need twelve steps. We’ll keep the source link so you can follow the full recipe.</p></article></div>}
function Empty({emoji,title,text}:{emoji:string;title:string;text:string}){return <div className="empty"><span>{emoji}</span><h2>{title}</h2><p>{text}</p></div>}
