import type { Recipe } from './types'
export const recipes: Recipe[] = [
 {id:'r1',title:'Creamy Coconut Peanut Noodles',blurb:'Silky, savoury and suspiciously easy.',time:20,serves:4,tags:['Quick','Veggie'],colour:'#D98B5F',emoji:'🥜',ingredients:[{name:'noodles',amount:'400 g'},{name:'coconut milk',amount:'1 tin'},{name:'peanut butter',amount:'3 tbsp'},{name:'soy sauce',amount:'2 tbsp'},{name:'lime',amount:'1'},{name:'broccoli',amount:'1 head'}],method:['Whisk coconut milk, peanut butter and soy sauce.','Cook noodles and broccoli.','Toss together. Finish with lime.']},
 {id:'r2',title:'One-pan Lemon Chicken',blurb:'Golden chicken, crispy spuds, one pan. Lovely.',time:45,serves:4,tags:['Family','One pan'],colour:'#E3B94F',emoji:'🍋',ingredients:[{name:'chicken thighs',amount:'8'},{name:'baby potatoes',amount:'750 g'},{name:'lemon',amount:'2'},{name:'garlic',amount:'4 cloves'},{name:'green beans',amount:'250 g'}],method:['Heat oven to 210°C.','Roast chicken, potatoes, lemon and garlic for 35 minutes.','Add beans for the final 10 minutes.']},
 {id:'r3',title:'Actually Good Lentil Bolognese',blurb:'Nobody needs to know it started with lentils.',time:35,serves:6,tags:['Batch cook','Veggie'],colour:'#B75D4B',emoji:'🍝',ingredients:[{name:'red lentils',amount:'1½ cups'},{name:'tinned tomatoes',amount:'2 tins'},{name:'carrot',amount:'2'},{name:'onion',amount:'1'},{name:'spaghetti',amount:'500 g'}],method:['Soften chopped onion and carrot.','Add lentils, tomatoes and two cups water. Simmer 25 minutes.','Serve with spaghetti.']},
 {id:'r4',title:'Crispy Fish Tacos',blurb:'Weeknight dinner wearing a tiny party hat.',time:25,serves:4,tags:['Quick','Fresh'],colour:'#5A9A91',emoji:'🌮',ingredients:[{name:'white fish',amount:'600 g'},{name:'tortillas',amount:'12'},{name:'red cabbage',amount:'¼'},{name:'avocado',amount:'2'},{name:'lime',amount:'2'}],method:['Season and pan-fry fish.','Shred cabbage and slice avocado.','Pile into warm tortillas with lime.']},
 {id:'r5',title:'Tray-bake Pumpkin Gnocchi',blurb:'Tip it in. Roast it. Take the praise.',time:30,serves:4,tags:['One pan','Veggie'],colour:'#D27A38',emoji:'🎃',ingredients:[{name:'gnocchi',amount:'500 g'},{name:'pumpkin',amount:'600 g'},{name:'baby spinach',amount:'120 g'},{name:'feta',amount:'150 g'}],method:['Roast gnocchi and pumpkin at 220°C for 25 minutes.','Fold through spinach.','Crumble over feta.']},
 {id:'r6',title:'Beef & Broccoli Stir-fry',blurb:'Faster than delivery. Nearly as little washing up.',time:20,serves:4,tags:['Quick','Family'],colour:'#47775C',emoji:'🥦',ingredients:[{name:'beef strips',amount:'500 g'},{name:'broccoli',amount:'2 heads'},{name:'rice',amount:'2 cups'},{name:'soy sauce',amount:'3 tbsp'},{name:'ginger',amount:'1 knob'}],method:['Cook rice.','Stir-fry beef, then broccoli and ginger.','Add soy sauce and serve.']},
 {id:'r7',title:'Cosy Chicken Curry',blurb:'Mild, comforting and very good at becoming lunch.',time:40,serves:6,tags:['Batch cook','Family'],colour:'#C99C42',emoji:'🍛',ingredients:[{name:'chicken breast',amount:'700 g'},{name:'coconut milk',amount:'1 tin'},{name:'curry paste',amount:'3 tbsp'},{name:'sweet potato',amount:'2'},{name:'rice',amount:'2 cups'}],method:['Brown chicken and curry paste.','Add sweet potato and coconut milk. Simmer 25 minutes.','Serve with rice.']},
 {id:'r8',title:'Green Goddess Frittata',blurb:'For when the crisper drawer needs an intervention.',time:30,serves:4,tags:['Fridge raid','Veggie'],colour:'#82A35B',emoji:'🥚',ingredients:[{name:'eggs',amount:'8'},{name:'baby spinach',amount:'100 g'},{name:'zucchini',amount:'1'},{name:'feta',amount:'100 g'}],method:['Whisk eggs.','Cook grated zucchini and spinach in an ovenproof pan.','Add eggs and feta. Bake until set.']},
 {id:'r9',title:'Sausage, Tomato & Bean Pot',blurb:'A proper dinner from mostly tins. No shame here.',time:35,serves:4,tags:['Budget','One pot'],colour:'#A75042',emoji:'🥘',ingredients:[{name:'sausages',amount:'8'},{name:'tinned tomatoes',amount:'1 tin'},{name:'cannellini beans',amount:'1 tin'},{name:'onion',amount:'1'},{name:'bread',amount:'1 loaf'}],method:['Brown sausages.','Add onion, tomatoes and beans.','Simmer 20 minutes and serve with bread.']},
 {id:'r10',title:'Sticky Salmon Rice Bowls',blurb:'Looks impressive. Knows it only took 25 minutes.',time:25,serves:4,tags:['Quick','Fresh'],colour:'#D46F67',emoji:'🍣',ingredients:[{name:'salmon fillets',amount:'4'},{name:'rice',amount:'2 cups'},{name:'cucumber',amount:'1'},{name:'soy sauce',amount:'3 tbsp'},{name:'honey',amount:'2 tbsp'}],method:['Cook rice.','Glaze salmon with soy and honey, then bake.','Serve with sliced cucumber.']},
 {id:'r11',title:'Cheesy Hidden-Veg Quesadillas',blurb:'Vegetables in a cheese disguise. Everyone wins.',time:20,serves:4,tags:['Kids','Quick'],colour:'#D4A33A',emoji:'🧀',ingredients:[{name:'tortillas',amount:'8'},{name:'cheddar',amount:'250 g'},{name:'corn',amount:'1 tin'},{name:'zucchini',amount:'1'},{name:'capsicum',amount:'1'}],method:['Grate zucchini and chop capsicum.','Fill tortillas with vegetables and cheese.','Toast both sides until golden.']},
 {id:'r12',title:'Sunday-ish Roast Lamb',blurb:'All the comfort, none of the ceremonial fuss.',time:75,serves:6,tags:['Weekend','Family'],colour:'#7D6356',emoji:'🍖',ingredients:[{name:'lamb leg',amount:'1.5 kg'},{name:'potatoes',amount:'1 kg'},{name:'carrot',amount:'4'},{name:'rosemary',amount:'4 sprigs'},{name:'garlic',amount:'6 cloves'}],method:['Heat oven to 200°C.','Roast lamb and vegetables for 60–70 minutes.','Rest lamb before carving. Seriously.']}
]
export const days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
