import { useEffect, useRef, useState } from 'react'
import type { PantryItem, Plan, Recipe } from './types'
import { supabase } from './supabase'

export function useCooksmithData(userId:string){
 const [personal,setPersonal]=useState<Recipe[]>([]); const [pantry,setPantry]=useState<PantryItem[]>([]); const [plan,setPlan]=useState<Plan>({}); const [loading,setLoading]=useState(true); const household=useRef(''); const loaded=useRef(false)
 useEffect(()=>{let active=true;(async()=>{const {data:profile,error}=await supabase.from('profiles').select('household_id').eq('id',userId).single();if(error||!profile){setLoading(false);return}household.current=profile.household_id;const [rr,pp,mm]=await Promise.all([supabase.from('recipes').select('*').eq('household_id',profile.household_id),supabase.from('pantry_items').select('*').eq('household_id',profile.household_id).order('created_at',{ascending:false}),supabase.from('meal_plan_items').select('*').eq('household_id',profile.household_id)]);if(!active)return;setPersonal((rr.data||[]).map(r=>({id:r.id,title:r.title,blurb:r.blurb||'A household classic. Or at least worth another go.',time:r.time_minutes||30,serves:r.serves||4,tags:r.tags||['Mine'],colour:r.colour||'#8B6E59',emoji:r.emoji||'🍽️',ingredients:r.ingredients||[],method:r.method||[],sourceUrl:r.source_url||undefined,personal:true})));setPantry((pp.data||[]).map(p=>({id:p.id,name:p.name,amount:p.amount,checked:p.checked})));setPlan(Object.fromEntries((mm.data||[]).map(m=>[m.day_key,m.recipe_id])));loaded.current=true;setLoading(false)})();return()=>{active=false}},[userId])
 useEffect(()=>{if(!loaded.current||!household.current)return;const timer=setTimeout(async()=>{await supabase.from('recipes').delete().eq('household_id',household.current);if(personal.length)await supabase.from('recipes').insert(personal.map(r=>({id:r.id,household_id:household.current,created_by:userId,title:r.title,blurb:r.blurb,time_minutes:r.time,serves:r.serves,tags:r.tags,colour:r.colour,emoji:r.emoji,ingredients:r.ingredients,method:r.method,source_url:r.sourceUrl||null})))},350);return()=>clearTimeout(timer)},[personal,userId])
 useEffect(()=>{if(!loaded.current||!household.current)return;const timer=setTimeout(async()=>{await supabase.from('pantry_items').delete().eq('household_id',household.current);if(pantry.length)await supabase.from('pantry_items').insert(pantry.map(p=>({id:p.id,household_id:household.current,name:p.name,amount:p.amount,checked:Boolean(p.checked)})))},350);return()=>clearTimeout(timer)},[pantry])
 useEffect(()=>{if(!loaded.current||!household.current)return;const timer=setTimeout(async()=>{await supabase.from('meal_plan_items').delete().eq('household_id',household.current);const rows=Object.entries(plan).filter(([,id])=>id).map(([day,recipeId])=>({household_id:household.current,day_key:day,recipe_id:recipeId}));if(rows.length)await supabase.from('meal_plan_items').insert(rows)},350);return()=>clearTimeout(timer)},[plan])
 return {personal,setPersonal,pantry,setPantry,plan,setPlan,loading}
}
